'use client';
import {useEffect,useRef,useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {ArrowRight,Check} from 'lucide-react';
import {track} from '../tracking';
const interests:Record<string,string>={college:'College / placement partnership',upskilling:'Enterprise upskilling',hiring:'Hiring waitlist',events:'Webinar / event interest',story:'Share a customer story',general:'General enquiry'};
export function ContactForm(){const [interest,setInterest]=useState('general'),[consent,setConsent]=useState(false),[state,setState]=useState<'idle'|'saving'|'success'|'error'>('idle'),[message,setMessage]=useState('');const requestId=useRef(''),started=useRef(false);
useEffect(()=>{const v=new URLSearchParams(location.search).get('interest');if(v&&interests[v])setInterest(v);requestId.current=crypto.randomUUID();},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(state==='saving')return;if(!consent){setMessage('Please confirm that we may respond to your request.');setState('error');return;}const form=new FormData(e.currentTarget),q=new URLSearchParams(location.search);setState('saving');setMessage('');const attribution=Object.fromEntries(['utm_source','utm_medium','utm_campaign','campaign'].map(k=>[k,(q.get(k)||'').slice(0,100)]));try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,...Object.fromEntries(form),interest,consent,source:location.pathname,attribution})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Your request could not be saved. Please try again.');setState('success');setMessage(interest==='hiring'?'You’re on the hiring waitlist. Your interest has been saved.':'Thank you. Your enquiry has been saved for the Pathwisse team.');track(interest==='hiring'?'waitlist_submit':'lead_submit',interest);}catch(e){setState('error');setMessage(e instanceof Error?e.message:'We couldn’t save your request. Your details are still here—please try again.');track('form_error',interest);}}
return <form className="contact-form" onSubmit={submit} onFocus={()=>{if(!started.current){track('form_start',interest);started.current=true;}}}>{state==='success'?<div className="form-success"><Check size={30}/><h2>One step closer.</h2><p role="status">{message}</p><p className="form-note">We have not booked a meeting or sent an email automatically.</p><a className="text-link" href="/">Back to Pathwisse <ArrowRight size={15}/></a></div>:<><div className="field"><label htmlFor="interest">I’m interested in</label><Select value={interest} onValueChange={setInterest}><SelectTrigger id="interest" aria-label="I’m interested in"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(interests).map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div><div className="field"><label htmlFor="name">Full name *</label><input id="name" name="name" autoComplete="name" required maxLength={100} placeholder="Your name"/></div><div className="field"><label htmlFor="email">Email address *</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@company.com"/></div><div className="field"><label htmlFor="organization">Organization {['college','upskilling','hiring'].includes(interest)?'*':'(optional)'}</label><input id="organization" name="organization" autoComplete="organization" required={['college','upskilling','hiring'].includes(interest)} maxLength={160} placeholder="Your institution or company"/></div><div className="field"><label htmlFor="message">What would you like to explore? (optional)</label><textarea id="message" name="message" maxLength={2000} placeholder="Tell us about your goals, team, or cohort."/></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><div className="consent-row"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">I agree that Pathwisse may use these details to respond to this enquiry or the updates I requested. <a href="/privacy">Read the data notice.</a></label></div>{state==='error'&&<p className="form-message" role="alert">{message}</p>}<button className="button" disabled={state==='saving'} type="submit">{state==='saving'?'Saving your request…':interest==='hiring'?'Join the hiring waitlist':'Send enquiry'}<ArrowRight size={16}/></button><p className="form-note">No unrelated marketing subscription. Please don’t share confidential information.</p></>}</form>}

