'use client';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { AudioLines,ArrowUpRight,Check,ArrowRight } from 'lucide-react';
import { Dashboard } from './site';
export function Experience({kind}:{kind:string}){
if(kind==='student')return <Dashboard/>;
if(kind==='voice')return <div className="voice-demo"><div className="voice-orb"><AudioLines size={52}/></div><h3>What could come next?</h3><p>Your interests. Your strengths. Your possibilities.</p><a className="button" href="https://careervoice.pathwisse.com">Open Career Voice <ArrowUpRight size={16}/></a><small>Explore the live product on its own site.</small></div>;
const college=kind==='college',hire=kind==='hiring';
return <div className="evidence-demo"><div className="evidence-title"><span className="eyebrow">{college?'PLACEMENT INTELLIGENCE':hire?'TALENT INTELLIGENCE':'WORKFORCE CAPABILITY'}</span><h3>{college?'See the cohort. Find the next step.':hire?'A candidate’s work, in context.':'Close the gap. Open a possibility.'}</h3><small>Illustrative concept · Sample data{hire?' · Product in development':''}</small></div><Tabs defaultValue="gaps"><TabsList className="demo-tabs"><TabsTrigger value="gaps">{hire?'Skill evidence':'Skill gaps'}</TabsTrigger><TabsTrigger value="path">{hire?'Project evidence':'Learning path'}</TabsTrigger><TabsTrigger value="proof">{hire?'Review context':'Readiness'}</TabsTrigger></TabsList><TabsContent value="gaps"><Table><TableHeader><TableRow><TableHead>{college?'Target role':hire?'Capability':'Team'}</TableHead><TableHead>{hire?'Evidence':'Current signal'}</TableHead><TableHead>Next step</TableHead></TableRow></TableHeader><TableBody>{(hire?[['SQL','Documented queries','Review assumptions'],['Data storytelling','Dashboard + narrative','Discuss decisions'],['Problem framing','Project brief','Clarify trade-offs']]:college?[['Data analysts','SQL needs practice','Query project'],['Developers','Accessibility gap','Keyboard review'],['Business analysts','Evidence developing','Case narrative']]:[['Operations','Data interpretation gap','Data literacy path'],['Product','SQL developing','Customer analysis'],['Engineering','Accessibility gap','Interface review']]).map(x=><TableRow key={x[0]}>{x.map((v,i)=><TableCell key={v}>{i===1?<span className="evidence-chip">{v}</span>:v}</TableCell>)}</TableRow>)}</TableBody></Table><p className="demo-note">Signals connect to work samples and agreed role expectations.</p></TabsContent><TabsContent value="path"><div className="learning-demo">{[['01','Define the question','A clear brief and success criteria'],['02','Practice the skill','Focused exercises and feedback'],['03','Apply it to a project','A customer insights dashboard'],['04','Review the evidence','Explain decisions and limitations']].map((x,i)=><div key={x[0]}><span>{i===0?<Check size={15}/>:x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><ArrowRight size={15}/></div>)}</div></TabsContent><TabsContent value="proof"><div className="proof-demo"><div><span className="eyebrow">APPLIED WORK</span><h4>Customer insights dashboard</h4><p>Query logic, documented assumptions, clear visual explanation.</p><a href="/projects/customer-insights" className="text-link">Read the project brief <ArrowUpRight size={15}/></a></div><div className="proof-checks"><span><Check size={15}/>Problem explained</span><span><Check size={15}/>Work inspectable</span><span><Check size={15}/>Limitations stated</span></div></div><p className="demo-note">Evidence informs a review. It does not guarantee placement, performance, or a hiring outcome.</p></TabsContent></Tabs></div>}

