export interface EngineeringStream {
  id: string;
  name: string;
  rolesCount: number;
  rolesWithPublishedPath: number;
  roles: EngineeringRole[];
}

export interface EngineeringRole {
  id: string;
  title: string;
  streamId: string;
  streamName: string;
  hasPublishedPath: boolean;
  level: 'Entry Level';
}

export const ENGINEERING_STREAMS: EngineeringStream[] = [
  {
    id: 'cse',
    name: 'Computer Science Engineering',
    rolesCount: 26,
    rolesWithPublishedPath: 26,
    roles: [
      { id: 'cse-01', title: 'Full Stack Developer (Junior)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-02', title: 'Frontend Engineer (React/Angular/Next.js)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-03', title: 'Backend Engineer (Node/Python/Go)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-04', title: 'Data Analyst (BI & Visualization)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-05', title: 'Junior Data Engineer', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-06', title: 'Automation QA (Selenium)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-07', title: 'Junior DevOps Engineer', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-08', title: 'Cloud Support Associate (AWS/Azure)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-09', title: 'Junior Machine Learning Engineer', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-10', title: 'Cybersecurity Analyst (SOC Tier 1)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-11', title: 'Mobile App Developer (Flutter/React Native)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-12', title: 'iOS Application Developer Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-13', title: 'Android Developer Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-14', title: 'Systems Software Engineer (C/C++)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-15', title: 'Database Administrator Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-16', title: 'Technical Support Engineer (L1)', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-17', title: 'API Integration Specialist Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-18', title: 'Data Quality Analyst Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-19', title: 'Site Reliability Engineering Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-20', title: 'Network Operations Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-21', title: 'Information Security Associate Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-22', title: 'Manual & Exploratory QA Tester', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-23', title: 'ETL Developer Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-24', title: 'Junior Data Scientist', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-25', title: 'Embedded Linux Programmer Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'cse-26', title: 'Microservices Developer Trainee', streamId: 'cse', streamName: 'Computer Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'civil',
    name: 'Civil Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'civ-01', title: 'Junior Site Engineer', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-02', title: 'CAD Draftsman (Civil)', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-03', title: 'Junior Quantity Surveyor', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-04', title: 'BIM Modelling Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-05', title: 'Junior Structural Design Engineer', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-06', title: 'Geotechnical Site Investigator Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-07', title: 'Highway & Transportation Design Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-08', title: 'Construction Billing & Estimation Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-09', title: 'Water Resource & Hydrology Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-10', title: 'Quality Control / QA Lab Engineer (Civil)', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-11', title: 'Surveying & Total Station Technician Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-12', title: 'Environmental Site Assessment Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-13', title: 'Urban Planning Assistant Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-14', title: 'Junior Safety & Compliance Officer (Site)', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'civ-15', title: 'Precast Concrete Plant Trainee', streamId: 'civil', streamName: 'Civil Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'mech',
    name: 'Mechanical Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'mec-01', title: 'CAD Design Engineer (SolidWorks/CATIA)', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-02', title: 'Junior Quality Engineer (QC/QA)', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-03', title: 'HVAC Design Engineer Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-04', title: 'Piping Design Engineer Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-05', title: 'FEA / Structural Simulation Analyst Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-06', title: 'Thermal Systems Design Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-07', title: 'CNC Machine Programmer Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-08', title: 'Automotive Powertrain Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-09', title: 'Plant Maintenance Engineer Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-10', title: 'Hydraulics & Pneumatics Systems Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-11', title: 'Robotic Welding Cell Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-12', title: 'Production Planning Trainee (Mechanical)', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-13', title: 'Product Development & Prototyping Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-14', title: 'Tool Design Engineer Trainee (Jigs & Fixtures)', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mec-15', title: 'Reliability Engineering Trainee', streamId: 'mech', streamName: 'Mechanical Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'elec',
    name: 'Electrical Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'ele-01', title: 'Junior Electrical Design Engineer', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-02', title: 'PLC / SCADA Programmer Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-03', title: 'EV / Battery Systems Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-04', title: 'Power Distribution & Substation Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-05', title: 'Switchgear & Protection Testing Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-06', title: 'Solar PV Systems Design Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-07', title: 'Control Panel Design Engineer Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-08', title: 'Transformer Testing & Commissioning Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-09', title: 'Power Electronics Applications Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-10', title: 'Building Electrical (MEP) Draftsman Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-11', title: 'Motor Drives & Inverters Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-12', title: 'Electrical Safety & Compliance Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-13', title: 'Industrial Energy Audit Associate Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-14', title: 'Instrumentation Calibration Technician Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'ele-15', title: 'Wind Turbine Electrical Systems Trainee', streamId: 'elec', streamName: 'Electrical Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'chem',
    name: 'Chemical Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'che-01', title: 'Graduate Process Engineer Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-02', title: 'Junior Quality Control Chemist', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-03', title: 'Pharma Process Engineer Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-04', title: 'P&ID & Process Simulation (Aspen) Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-05', title: 'Petrochemical Refining Operations Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-06', title: 'Polymer Manufacturing Technician Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-07', title: 'Process Safety Management (PSM) Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-08', title: 'Water & Wastewater Treatment Plant Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-09', title: 'Catalyst Testing & Evaluation Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-10', title: 'Chemical Plant DCS Operator Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-11', title: 'Bio-Process Fermentation Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-12', title: 'Industrial Hygiene & Chemical Safety Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-13', title: 'Pilot Plant Research Associate Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-14', title: 'Fertilizer Production Operations Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'che-15', title: 'Battery Chemical Material Synthesis Trainee', streamId: 'chem', streamName: 'Chemical Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'biomed',
    name: 'Biomedical Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'bio-01', title: 'Junior Biomedical Equipment Technician', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-02', title: 'Clinical Application Specialist Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-03', title: 'Quality Engineer (Medical Devices)', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-04', title: 'Medical Device Regulatory Affairs Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-05', title: 'Biomaterials Testing Technician Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-06', title: 'Medical Imaging System Service Trainee (X-Ray/MRI)', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-07', title: 'Prosthetics & Orthotics Design Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-08', title: 'Hospital Clinical Engineering Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-09', title: 'Patient Monitoring System QA Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-10', title: 'Digital Health Software Tester Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-11', title: 'Biosensor Development Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-12', title: 'Microfluidic Chip Fabrication Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-13', title: 'Surgical Robotics Maintenance Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-14', title: 'Physiological Signal Processing Trainee (ECG/EEG)', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'bio-15', title: 'Medical Device Calibration Specialist Trainee', streamId: 'biomed', streamName: 'Biomedical Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'aero',
    name: 'Aerospace Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 15,
    roles: [
      { id: 'aer-01', title: 'UAV / Drone Design Engineer Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-02', title: 'CFD / Aerodynamics Analyst Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-03', title: 'Avionics Systems Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-04', title: 'Aerospace Structures Stress Analyst Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-05', title: 'Gas Turbine Propulsion Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-06', title: 'Aircraft Maintenance & Overhaul (MRO) Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-07', title: 'Flight Control & Guidance Systems Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-08', title: 'Composite Materials Fabrication Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-09', title: 'Rocket Propulsion & Thermal Systems Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-10', title: 'Satellite Systems Assembly & Test Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-11', title: 'Aerospace Quality Assurance (AS9100) Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-12', title: 'Wind Tunnel Testing Technician Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-13', title: 'Aircraft Weight & Balance Estimator Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-14', title: 'Space Mission Planning Assistant Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'aer-15', title: 'Radar & Telemetry Station Trainee', streamId: 'aero', streamName: 'Aerospace Engineering', hasPublishedPath: true, level: 'Entry Level' },
    ],
  },
  {
    id: 'ece',
    name: 'Electronics & Communication Engg',
    rolesCount: 15,
    rolesWithPublishedPath: 0,
    roles: [
      { id: 'ece-01', title: 'Junior Hardware Engineer', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-02', title: 'Embedded Systems Engineer Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-03', title: 'VLSI Design Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-04', title: 'PCB Design Engineer Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-05', title: 'FPGA Programmer Trainee (Verilog/VHDL)', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-06', title: 'RF & Microwave Circuit Testing Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-07', title: '5G / Telecom Protocol Testing Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-08', title: 'IoT Device Firmware Developer Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-09', title: 'Semiconductor Fabrication Operations Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-10', title: 'Digital Signal Processing (DSP) Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-11', title: 'Optical Fiber Network Technician Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-12', title: 'Automotive ECU Calibration Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-13', title: 'EMI / EMC Compliance Testing Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-14', title: 'Consumer Electronics QA Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ece-15', title: 'Wireless Sensor Network Field Trainee', streamId: 'ece', streamName: 'Electronics & Communication Engg', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
  {
    id: 'env',
    name: 'Environmental Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 0,
    roles: [
      { id: 'env-01', title: 'Sustainability Analyst Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-02', title: 'ESG Data Analyst Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-03', title: 'Junior Environmental Consultant', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-04', title: 'Air Quality Monitoring Technician Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-05', title: 'Effluent Treatment Plant (ETP) Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-06', title: 'Carbon Accounting & Footprint Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-07', title: 'Solid Waste Management Planner Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-08', title: 'Environmental Impact Assessment (EIA) Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-09', title: 'Hazardous Waste Compliance Officer Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-10', title: 'Water Resource GIS Analyst Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-11', title: 'Noise & Vibration Assessment Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-12', title: 'Industrial Wastewater Compliance Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-13', title: 'Renewable Energy Integration Analyst Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-14', title: 'Ecological Restoration Project Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'env-15', title: 'Soil Remediation Specialist Trainee', streamId: 'env', streamName: 'Environmental Engineering', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
  {
    id: 'ime',
    name: 'Industrial & Manufacturing Engg',
    rolesCount: 15,
    rolesWithPublishedPath: 0,
    roles: [
      { id: 'ime-01', title: 'Supply Chain Analyst Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-02', title: 'CAM / CNC Programmer Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-03', title: 'Production Planning & Control (PPC) Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-04', title: 'Lean Manufacturing & Kaizen Facilitator Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-05', title: 'Quality Assurance & Six Sigma Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-06', title: 'Plant Layout & Operations Research Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-07', title: 'Inventory Optimization Analyst Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-08', title: 'Warehouse Automation Associate Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-09', title: 'Work Study & Ergonomics Analyst Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-10', title: 'Manufacturing Execution System (MES) Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-11', title: 'Supplier Quality Auditor Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-12', title: 'Packaging Design & Logistics Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-13', title: 'Tool Crib & Fixture Management Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-14', title: 'Total Productive Maintenance (TPM) Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'ime-15', title: 'Assembly Line Balancing Specialist Trainee', streamId: 'ime', streamName: 'Industrial & Manufacturing Engg', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
  {
    id: 'petro',
    name: 'Petroleum Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 0,
    roles: [
      { id: 'pet-01', title: 'Drilling Engineer Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-02', title: 'Junior Reservoir Engineer', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-03', title: 'Production Operations Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-04', title: 'Well Logging & Petrophysics Analyst Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-05', title: 'Mud Logging & Fluids Technician Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-06', title: 'Subsea Wellhead Installation Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-07', title: 'Pipeline Integrity & Corrosion Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-08', title: 'Enhanced Oil Recovery (EOR) Lab Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-09', title: 'Offshore Rig Safety Specialist Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-10', title: 'Gas Processing Plant Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-11', title: 'Well Intervention & Workover Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-12', title: 'Seismic Data Interpretation Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-13', title: 'LNG Storage & Regasification Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-14', title: 'Oilfield Chemical Optimization Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'pet-15', title: 'Refinery Process Economics Analyst Trainee', streamId: 'petro', streamName: 'Petroleum Engineering', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
  {
    id: 'robotics',
    name: 'Robotics & Automation Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 1,
    roles: [
      { id: 'rob-01', title: 'ROS Developer (Junior)', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-02', title: 'Computer Vision Engineer Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-03', title: 'PLC / SCADA Automation Engineer (Entry)', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-04', title: 'AI/ML for Robotics Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'rob-05', title: 'Industrial Robot Arm Programmer Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-06', title: 'Autonomous Mobile Robot (AMR) Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-07', title: 'Sensor Fusion & SLAM Engineer Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-08', title: 'Mechatronics Integration Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-09', title: 'Embedded RTOS Robotics Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-10', title: 'Motion Control Systems Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-11', title: 'Robotics Simulation & Gazebo Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-12', title: 'Automated Guided Vehicle (AGV) Service Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-13', title: 'End-Effector & Gripper Design Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-14', title: 'Cobot (Collaborative Robot) Deployment Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'rob-15', title: 'Inspection Drone Systems Trainee', streamId: 'robotics', streamName: 'Robotics & Automation Engineering', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
  {
    id: 'materials',
    name: 'Materials Science Engineering',
    rolesCount: 15,
    rolesWithPublishedPath: 1,
    roles: [
      { id: 'mat-01', title: 'Junior Metallurgist', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-02', title: 'Materials Testing Technician / Engineer (Entry)', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-03', title: 'Graduate Materials Engineer Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: true, level: 'Entry Level' },
      { id: 'mat-04', title: 'Non-Destructive Testing (NDT) Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-05', title: 'Corrosion Control Specialist Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-06', title: 'Ceramics & Refractory Materials Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-07', title: 'Polymer Compound Development Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-08', title: 'Additive Manufacturing (Metal 3D Printing) Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-09', title: 'Failure Analysis Lab Assistant Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-10', title: 'Heat Treatment Process Controller Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-11', title: 'Semiconductor Thin-Film Materials Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-12', title: 'Foundry & Casting Quality Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-13', title: 'Composite Matrix Formulation Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-14', title: 'Nanomaterials Characterization Trainee (SEM/XRD)', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
      { id: 'mat-15', title: 'Surface Coating & Electroplating Trainee', streamId: 'materials', streamName: 'Materials Science Engineering', hasPublishedPath: false, level: 'Entry Level' },
    ],
  },
];

export const ALL_ROLES: EngineeringRole[] = ENGINEERING_STREAMS.flatMap((s) => s.roles);
