import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';

export const leads = sqliteTable('leads', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone').notNull().default(''),
  organization: text('organization').notNull().default(''),
  organizationType: text('organization_type').notNull().default(''),
  designation: text('designation').notNull().default(''),
  interest: text('interest').notNull(),
  message: text('message').notNull().default(''),
  audience: text('audience').notNull().default(''),
  campaignId: text('campaign_id').notNull().default(''),
  campaignName: text('campaign_name').notNull().default(''),
  source: text('source').notNull(),
  landingPage: text('landing_page').notNull().default(''),
  referrer: text('referrer').notNull().default(''),
  utmSource: text('utm_source').notNull().default(''),
  utmMedium: text('utm_medium').notNull().default(''),
  utmCampaign: text('utm_campaign').notNull().default(''),
  utmTerm: text('utm_term').notNull().default(''),
  utmContent: text('utm_content').notNull().default(''),
  attribution: text('attribution').notNull().default('{}'),
  consent: integer('consent').notNull(),
  leadStatus: text('lead_status').notNull().default('new'),
  leadScore: integer('lead_score').notNull().default(0),
  owner: text('owner').notNull().default(''),
  crmSyncStatus: text('crm_sync_status').notNull().default('not_configured'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [
  index('leads_email_created').on(t.email, t.createdAt),
  index('leads_campaign_created').on(t.campaignId, t.createdAt),
]);

export const events = sqliteTable('events', {
  id: integer('id').primaryKey({autoIncrement: true}),
  event: text('event').notNull(),
  page: text('page').notNull(),
  target: text('target').notNull().default(''),
  properties: text('properties').notNull().default('{}'),
  sessionId: text('session_id').notNull().default(''),
  consentVersion: text('consent_version').notNull().default(''),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const careerAudits = sqliteTable('career_audits', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull().default(''),
  email: text('email').notNull().default(''),
  answers: text('answers').notNull().default('{}'),
  recommendedRole: text('recommended_role').notNull(),
  readinessScore: integer('readiness_score').notNull().default(0),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [
  index('career_audits_role_created').on(t.recommendedRole, t.createdAt),
  index('career_audits_email_created').on(t.email, t.createdAt),
]);

export const blogPosts = sqliteTable('blog_posts', {
  slug: text('slug').primaryKey(),
  title: text('title').notNull(),
  excerpt: text('excerpt').notNull(),
  body: text('body').notNull(),
  heroImage: text('hero_image').notNull().default(''),
  ogImage: text('og_image').notNull().default(''),
  author: text('author').notNull().default('Pathwisse Team'),
  authorBio: text('author_bio').notNull().default(''),
  category: text('category').notNull(),
  tags: text('tags').notNull().default('[]'),
  publishDate: text('publish_date').notNull(),
  modifiedDate: text('modified_date').notNull(),
  status: text('status').notNull().default('draft'),
  featured: integer('featured').notNull().default(0),
  seoTitle: text('seo_title').notNull(),
  metaDescription: text('meta_description').notNull(),
  canonical: text('canonical').notNull().default(''),
  audience: text('audience').notNull().default('all'),
  relatedCareers: text('related_careers').notNull().default('[]'),
  relatedSkills: text('related_skills').notNull().default('[]'),
  relatedProducts: text('related_products').notNull().default('[]'),
  relatedGuides: text('related_guides').notNull().default('[]'),
  ctaType: text('cta_type').notNull().default('demo'),
  ctaUrl: text('cta_url').notNull().default('/contact'),
  faq: text('faq').notNull().default('[]'),
  references: text('references').notNull().default('[]'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [
  index('blog_status_date').on(t.status, t.publishDate),
  index('blog_category').on(t.category),
]);

export const careerRoles = sqliteTable('career_roles', {
  slug: text('slug').primaryKey(),
  roleName: text('role_name').notNull(),
  streamName: text('stream_name').notNull(),
  roleHook: text('role_hook').notNull(),
  whatWorkLooksLike: text('what_work_looks_like').notNull(),
  problemsSolves: text('problems_solves').notNull(),
  skillCount: integer('skill_count').notNull().default(15),
  topSkills: text('top_skills').notNull().default('[]'),
  proofProject: text('proof_project').notNull(),
  evidenceToShow: text('evidence_to_show').notNull(),
  pathwisseApproach: text('pathwisse_approach').notNull(),
  roleCta: text('role_cta').notNull().default('Try for Free on Pathwisse'),
  referenceSkill: text('reference_skill').notNull().default(''),
  referenceBook: text('reference_book').notNull().default(''),
  referenceAuthor: text('reference_author').notNull().default(''),
  onetBenchmark: text('onet_benchmark').notNull().default(''),
  externalUrl: text('external_url').notNull().default(''),
  seoTitle: text('seo_title').notNull(),
  metaDescription: text('meta_description').notNull(),
  faq: text('faq').notNull().default('[]'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [
  index('career_roles_stream').on(t.streamName),
]);

